### ISSUE TITLE
c-stick

### ISSUE THREAD

**Issue by Rhyslan** [Ordinaryperson2/3DSController#25]
I've found that the c-stick does not register as an input. I've tried it as the mouse, joystick1 and joystick2 and none of them get input. Not sure if this is a bug in the code or a setting I'm forgetting to set.

EDIT: I forgot to add that the zl and zr buttons do not register either

**Comment by slenered** [comment]
I had the same problem so I fixed it, and made a few changes myself...
https://github.com/slenered/3DSController/releases/tag/0.7

**Comment by slenered** [comment]
It works better for at least me

**Comment by Rhyslan** [comment]
Thanks, but do you have a .3dsx version?  I don't know how to use .cia files and don't need or want to add CFW.

**Comment by slenered** [comment]
I'll take a look

**Comment by Rhyslan** [comment]
Thanks

**Comment by slenered** [comment]
I couldn't find one that's compatible, so here are some options;
 1. install CFW (It isn't difficult or very dangerous) use the hack guide https://3ds.hacks.guide/
 2. Compile 3DS folder for homebrew (I Tried, sry)
 3. don't use the c-stick or z buttions
I wish I could help you more.

**Comment by Rhyslan** [comment]
OK, I might try to compile it, but if it doesn't work I'll just not use the c-stick or z buttons because they aren't necessary.  Thanks for your help though.

**Comment by Rhyslan** [comment]
I couldn't get it to compile (never compiled anything before so I'm not surprised), but I did decide to install CFW and I can now use the zl, zr and c-stick with @slenered's version.  I still have one slight problem of button mapping with Steam, but that's not a big concern.

**Comment by Rhyslan** [comment]
Nevermind about Steam, I just wasn't mapping the buttons correctly.
